name: ci
on:
  push:
    branches:
      - master
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Cache Dependencies
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          path: ~/.cache/pip

      - name: Install Dependencies
        run: |
          pip install mkdocs-material mkdocs-roamlinks-plugin mkdocs-rss-plugin

      - name: Adjust Wikilinks for Alias
        run: |
          find . -type f -name "*.md" -exec sed -i -E 's/\[\[([^\|\]]+)\|([^\]]+)\]\]/\[\[\1\]\]/g' {} +

      - name: Build MkDocs Site
        run: mkdocs build --clean

      - name: Deploy to GitHub Pages
        run: mkdocs gh-deploy --force
