name: Deploy MkDocs Site
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install Dependencies
        run: |
          pip install mkdocs-material mkdocs-roamlinks-plugin mkdocs-rss-plugin

      - name: Rename Files and Folders
        run: |
          find ./docs/ -depth -name '* *' -execdir rename 's/ /_/g' "{}" \;
          find ./docs/ -depth -name '*á*' -execdir rename 's/á/a/g' "{}" \;
          find ./docs/ -depth -name '*é*' -execdir rename 's/é/e/g' "{}" \;
          find ./docs/ -depth -name '*í*' -execdir rename 's/í/i/g' "{}" \;
          find ./docs/ -depth -name '*ó*' -execdir rename 's/ó/o/g' "{}" \;
          find ./docs/ -depth -name '*ú*' -execdir rename 's/ú/u/g' "{}" \;
          find ./docs/ -depth -name '*ñ*' -execdir rename 's/ñ/n/g' "{}" \;

      - name: Update Wikilinks
        run: |
          find ./docs/ -type f -name "*.md" -exec sed -i -E \
              -e 's/\[\[([^\|\]]* )([^\|\]]*)\]\]/\[\[\1_\2\]\]/g' \
              -e 's/\[\[([^\|\]]*)á([^\|\]]*)\]\]/\[\[\1a\2\]\]/g' \
              -e 's/\[\[([^\|\]]*)é([^\|\]]*)\]\]/\[\[\1e\2\]\]/g' \
              -e 's/\[\[([^\|\]]*)í([^\|\]]*)\]\]/\[\[\1i\2\]\]/g' \
              -e 's/\[\[([^\|\]]*)ó([^\|\]]*)\]\]/\[\[\1o\2\]\]/g' \
              -e 's/\[\[([^\|\]]*)ú([^\|\]]*)\]\]/\[\[\1u\2\]\]/g' \
              -e 's/\[\[([^\|\]]*)ñ([^\|\]]*)\]\]/\[\[\1n\2\]\]/g' {} +

      - name: Build and Deploy
        run: |
          mkdocs build --clean
          mkdocs gh-deploy --force
